GCC = gcc
CFLAG = -Wall -Wextra -Werror
ARFLAGES = crs
NAME = libft.a
SRCS =  ft_memset.c ft_strlen.c ft_putchar_fd.c ft_strmapi.c \
		ft_atoi.c ft_putendl_fd.c ft_strncmp.c \
		ft_bzero.c  ft_putnbr_fd.c ft_strnstr.c ft_calloc.c \
		ft_putstr_fd.c ft_strrchr.c ft_isalnum.c \
		ft_split.c ft_strtrim.c ft_isalpha.c  ft_strchr.c \
		ft_substr.c ft_isascii.c  ft_strdup.c ft_tolower.c \
		ft_isdigit.c ft_memchr.c ft_striteri.c ft_toupper.c \
		ft_isprint.c ft_memcmp.c ft_strjoin.c ft_itoa.c \
		ft_memcpy.c ft_strlcat.c ft_memmove.c ft_strlcpy.c
OBJS = $(SRCS:.c=.o)
BNS_SRCS = ft_lstadd_front_bonus.c ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstlast_bonus.c \
		ft_lstnew_bonus.c ft_lstsize_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
		ft_lstmap_bonus.c
BNS_OBJS = $(BNS_SRCS:.c=.o)
HEADER = libft.h

ifdef BONUS_GUARD
	OBJ = $(OBJS) $(BNS_OBJS)
else
	OBJ = $(OBJS)
endif

all: $(NAME)

%.o: %.c $(HEADER)
	$(GCC) $(CFLAGS) -c $< -o $@ -I $(HEADER)

$(NAME): $(OBJ)
	$(AR) $(ARFLAGES) $(NAME) $^

clean:
	$(RM) $(OBJS) $(BNS_OBJS)

fclean: clean
	$(RM) $(NAME)
	
re: fclean all

bonus:
	make BONUS_GUARD=1 all
	
.PHONY: all clean fclean re bonus

